<script src="{{ asset('admin/dist/js/jquery-3.7.0.min.js') }}"></script>
<script src="{{ asset('admin/dist/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('admin/dist/js/popper.min.js') }}"></script>
<script src="{{ asset('admin/dist/js/tooltip.js') }}"></script>
<script src="{{ asset('admin/dist/js/jquery.nicescroll.min.js') }}"></script>
<script src="{{ asset('admin/dist/js/moment.min.js') }}"></script>
<script src="{{ asset('admin/dist/js/stisla.js') }}"></script>
<script src="{{ asset('admin/dist/js/jscolor.js') }}"></script>
<script src="{{ asset('admin/dist/js/bootstrap-tagsinput.min.js') }}"></script>
<script src="{{ asset('admin/dist/js/select2.full.min.js') }}"></script>
<script src="{{ asset('admin/dist/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('admin/dist/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('admin/dist/js/iziToast.min.js') }}"></script>
<script src="{{ asset('admin/dist/js/fontawesome-iconpicker.js') }}"></script>
<script src="{{ asset('admin/dist/js/air-datepicker.min.js') }}"></script>
<script src="{{ asset('admin/dist/tinymce/tinymce.min.js') }}"></script>
<script src="{{ asset('admin/dist/js/bootstrap4-toggle.min.js') }}"></script>

<script src="{{ asset('admin/dist/js/scripts.js') }}"></script>
<script src="{{ asset('admin/dist/js/custom.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js"></script>
